// Generated by the Supabase MCP server from the ProCircuit project schema
// (gpzpmrumwaqyfkyvqbgl) after migration
// 20260923120000_step_3_1_rankings_calendars.
// Do not hand-edit; regenerate after each migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      admin_actions: {
        Row: {
          action_type: string;
          admin_id: string;
          consequence: string;
          created_at: string;
          device: string | null;
          id: string;
          notified_player: boolean;
          player_id: string | null;
          reason: string | null;
          role_at_time: string;
          target: Json | null;
        };
        Insert: {
          action_type: string;
          admin_id: string;
          consequence: string;
          created_at?: string;
          device?: string | null;
          id?: string;
          notified_player?: boolean;
          player_id?: string | null;
          reason?: string | null;
          role_at_time: string;
          target?: Json | null;
        };
        Update: {
          action_type?: string;
          admin_id?: string;
          consequence?: string;
          created_at?: string;
          device?: string | null;
          id?: string;
          notified_player?: boolean;
          player_id?: string | null;
          reason?: string | null;
          role_at_time?: string;
          target?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: 'admin_actions_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      agent_runs: {
        Row: {
          agent_name: string;
          completed_at: string | null;
          cost_amount: number | null;
          cost_currency: string | null;
          id: string;
          inputs_hash: string;
          model: string;
          output: Json | null;
          player_id: string;
          prompt_version: string;
          schema_version: string;
          started_at: string;
          status: string;
          trigger_type: string;
        };
        Insert: {
          agent_name: string;
          completed_at?: string | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          id?: string;
          inputs_hash: string;
          model: string;
          output?: Json | null;
          player_id: string;
          prompt_version: string;
          schema_version: string;
          started_at: string;
          status: string;
          trigger_type: string;
        };
        Update: {
          agent_name?: string;
          completed_at?: string | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          id?: string;
          inputs_hash?: string;
          model?: string;
          output?: Json | null;
          player_id?: string;
          prompt_version?: string;
          schema_version?: string;
          started_at?: string;
          status?: string;
          trigger_type?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'agent_runs_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      agent_schedules: {
        Row: {
          agent_name: string;
          paused: boolean;
          player_id: string;
          prompt_overrides: Json;
          updated_at: string;
        };
        Insert: {
          agent_name: string;
          paused?: boolean;
          player_id: string;
          prompt_overrides?: Json;
          updated_at?: string;
        };
        Update: {
          agent_name?: string;
          paused?: boolean;
          player_id?: string;
          prompt_overrides?: Json;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'agent_schedules_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      alerts: {
        Row: {
          acknowledged_at: string | null;
          acknowledged_by: string | null;
          body: string;
          category: string;
          created_at: string;
          id: string;
          kind: string;
          link: string | null;
          role_owner: string | null;
          title: string;
        };
        Insert: {
          acknowledged_at?: string | null;
          acknowledged_by?: string | null;
          body: string;
          category: string;
          created_at?: string;
          id?: string;
          kind: string;
          link?: string | null;
          role_owner?: string | null;
          title: string;
        };
        Update: {
          acknowledged_at?: string | null;
          acknowledged_by?: string | null;
          body?: string;
          category?: string;
          created_at?: string;
          id?: string;
          kind?: string;
          link?: string | null;
          role_owner?: string | null;
          title?: string;
        };
        Relationships: [];
      };
      approval_consumptions: {
        Row: {
          agent_run_id: string | null;
          approval_id: string;
          consumed_at: string;
          payload_hash: string;
          player_id: string;
        };
        Insert: {
          agent_run_id?: string | null;
          approval_id: string;
          consumed_at?: string;
          payload_hash: string;
          player_id: string;
        };
        Update: {
          agent_run_id?: string | null;
          approval_id?: string;
          consumed_at?: string;
          payload_hash?: string;
          player_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'approval_consumptions_agent_run_id_fkey';
            columns: ['agent_run_id'];
            isOneToOne: false;
            referencedRelation: 'agent_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approval_consumptions_approval_id_fkey';
            columns: ['approval_id'];
            isOneToOne: true;
            referencedRelation: 'approvals';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approval_consumptions_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      approvals: {
        Row: {
          action_type: string;
          agent_run_id: string | null;
          approved_at: string;
          approved_by: string;
          device: string | null;
          id: string;
          payload: Json;
          player_id: string;
        };
        Insert: {
          action_type: string;
          agent_run_id?: string | null;
          approved_at?: string;
          approved_by: string;
          device?: string | null;
          id?: string;
          payload: Json;
          player_id: string;
        };
        Update: {
          action_type?: string;
          agent_run_id?: string | null;
          approved_at?: string;
          approved_by?: string;
          device?: string | null;
          id?: string;
          payload?: Json;
          player_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'approvals_agent_run_id_fkey';
            columns: ['agent_run_id'];
            isOneToOne: false;
            referencedRelation: 'agent_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approvals_approved_by_fkey';
            columns: ['approved_by'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approvals_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      budget_estimates: {
        Row: {
          created_at: string;
          currency: string;
          estimate_amount: number;
          estimated_at: string;
          id: string;
          label: string;
          player_id: string;
          status: string;
        };
        Insert: {
          created_at?: string;
          currency: string;
          estimate_amount: number;
          estimated_at?: string;
          id?: string;
          label: string;
          player_id: string;
          status?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          estimate_amount?: number;
          estimated_at?: string;
          id?: string;
          label?: string;
          player_id?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'budget_estimates_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      cases: {
        Row: {
          due_at: string | null;
          excerpt: string;
          id: string;
          kind: string;
          opened_at: string;
          opened_by_rule: string;
          outcome: string | null;
          player_id: string;
          resolved_at: string | null;
          resolved_by: string | null;
        };
        Insert: {
          due_at?: string | null;
          excerpt: string;
          id?: string;
          kind: string;
          opened_at?: string;
          opened_by_rule: string;
          outcome?: string | null;
          player_id: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
        };
        Update: {
          due_at?: string | null;
          excerpt?: string;
          id?: string;
          kind?: string;
          opened_at?: string;
          opened_by_rule?: string;
          outcome?: string | null;
          player_id?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'cases_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      check_ins: {
        Row: {
          created_at: string;
          date: string;
          id: string;
          player_id: string;
          sentence: string | null;
          source: string;
          value: number;
        };
        Insert: {
          created_at?: string;
          date: string;
          id?: string;
          player_id: string;
          sentence?: string | null;
          source: string;
          value: number;
        };
        Update: {
          created_at?: string;
          date?: string;
          id?: string;
          player_id?: string;
          sentence?: string | null;
          source?: string;
          value?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'check_ins_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      fact_corrections: {
        Row: {
          after: string;
          before: string | null;
          created_at: string;
          decided_at: string | null;
          decided_by: string | null;
          field: string;
          id: string;
          proposed_by: string | null;
          source: string;
          state: string;
          tournament_id: string;
        };
        Insert: {
          after: string;
          before?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          field: string;
          id?: string;
          proposed_by?: string | null;
          source: string;
          state?: string;
          tournament_id: string;
        };
        Update: {
          after?: string;
          before?: string | null;
          created_at?: string;
          decided_at?: string | null;
          decided_by?: string | null;
          field?: string;
          id?: string;
          proposed_by?: string | null;
          source?: string;
          state?: string;
          tournament_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'fact_corrections_tournament_id_fkey';
            columns: ['tournament_id'];
            isOneToOne: false;
            referencedRelation: 'tournaments';
            referencedColumns: ['id'];
          },
        ];
      };
      feed_status: {
        Row: {
          cadence: string;
          feed: string;
          id: string;
          issues: Json;
          last_result: string | null;
          last_run_at: string | null;
          next_expected_at: string;
          row_count: number | null;
          updated_at: string;
        };
        Insert: {
          cadence?: string;
          feed: string;
          id?: string;
          issues?: Json;
          last_result?: string | null;
          last_run_at?: string | null;
          next_expected_at: string;
          row_count?: number | null;
          updated_at?: string;
        };
        Update: {
          cadence?: string;
          feed?: string;
          id?: string;
          issues?: Json;
          last_result?: string | null;
          last_run_at?: string | null;
          next_expected_at?: string;
          row_count?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      financial_action_snoozes: {
        Row: {
          candidate_key: string;
          created_at: string;
          id: string;
          player_id: string;
          snoozed_until: string;
        };
        Insert: {
          candidate_key: string;
          created_at?: string;
          id?: string;
          player_id: string;
          snoozed_until: string;
        };
        Update: {
          candidate_key?: string;
          created_at?: string;
          id?: string;
          player_id?: string;
          snoozed_until?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'financial_action_snoozes_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      fx_rates_daily: {
        Row: {
          currency: string;
          date: string;
          fetched_at: string;
          rate_to_eur: number;
          source: string;
        };
        Insert: {
          currency: string;
          date: string;
          fetched_at?: string;
          rate_to_eur: number;
          source: string;
        };
        Update: {
          currency?: string;
          date?: string;
          fetched_at?: string;
          rate_to_eur?: number;
          source?: string;
        };
        Relationships: [];
      };
      insights: {
        Row: {
          body: Json | null;
          cost_amount: number | null;
          cost_currency: string | null;
          created_at: string;
          date: string;
          delivery: string;
          distress: Json | null;
          feedback: string | null;
          feedback_at: string | null;
          focus: string | null;
          focus_done: boolean;
          focus_done_at: string | null;
          id: string;
          inputs_hash: string;
          lang: string;
          memory: Json | null;
          model: string | null;
          pattern_flag: string | null;
          player_id: string;
          prompt_version: string | null;
          provenance: Json;
          schema_version: string | null;
          tone_check: Json | null;
        };
        Insert: {
          body?: Json | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          created_at?: string;
          date: string;
          delivery: string;
          distress?: Json | null;
          feedback?: string | null;
          feedback_at?: string | null;
          focus?: string | null;
          focus_done?: boolean;
          focus_done_at?: string | null;
          id?: string;
          inputs_hash: string;
          lang: string;
          memory?: Json | null;
          model?: string | null;
          pattern_flag?: string | null;
          player_id: string;
          prompt_version?: string | null;
          provenance: Json;
          schema_version?: string | null;
          tone_check?: Json | null;
        };
        Update: {
          body?: Json | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          created_at?: string;
          date?: string;
          delivery?: string;
          distress?: Json | null;
          feedback?: string | null;
          feedback_at?: string | null;
          focus?: string | null;
          focus_done?: boolean;
          focus_done_at?: string | null;
          id?: string;
          inputs_hash?: string;
          lang?: string;
          memory?: Json | null;
          model?: string | null;
          pattern_flag?: string | null;
          player_id?: string;
          prompt_version?: string | null;
          provenance?: Json;
          schema_version?: string | null;
          tone_check?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: 'insights_pattern_flag_fkey';
            columns: ['pattern_flag'];
            isOneToOne: false;
            referencedRelation: 'patterns';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'insights_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      ledger_lines: {
        Row: {
          amount_original: number;
          category: string;
          created_at: string;
          currency_original: string;
          date: string;
          edits: Json;
          fresh: boolean;
          fx_rate_date: string;
          id: string;
          player_id: string;
          receipt_ref: string | null;
          source: string;
          tournament_id: string | null;
          unsure_fields: Json;
          what: string;
        };
        Insert: {
          amount_original: number;
          category: string;
          created_at?: string;
          currency_original: string;
          date: string;
          edits?: Json;
          fresh?: boolean;
          fx_rate_date: string;
          id?: string;
          player_id: string;
          receipt_ref?: string | null;
          source: string;
          tournament_id?: string | null;
          unsure_fields?: Json;
          what: string;
        };
        Update: {
          amount_original?: number;
          category?: string;
          created_at?: string;
          currency_original?: string;
          date?: string;
          edits?: Json;
          fresh?: boolean;
          fx_rate_date?: string;
          id?: string;
          player_id?: string;
          receipt_ref?: string | null;
          source?: string;
          tournament_id?: string | null;
          unsure_fields?: Json;
          what?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ledger_lines_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      matches: {
        Row: {
          best_of: number | null;
          charted_by: string | null;
          court: string | null;
          final_tb: string | null;
          gender: string | null;
          match_date: string | null;
          match_id: string;
          match_time: string | null;
          player1: string | null;
          player1_hand: string | null;
          player2: string | null;
          player2_hand: string | null;
          round: string | null;
          surface: string | null;
          tournament: string | null;
          umpire: string | null;
        };
        Insert: {
          best_of?: number | null;
          charted_by?: string | null;
          court?: string | null;
          final_tb?: string | null;
          gender?: string | null;
          match_date?: string | null;
          match_id: string;
          match_time?: string | null;
          player1?: string | null;
          player1_hand?: string | null;
          player2?: string | null;
          player2_hand?: string | null;
          round?: string | null;
          surface?: string | null;
          tournament?: string | null;
          umpire?: string | null;
        };
        Update: {
          best_of?: number | null;
          charted_by?: string | null;
          court?: string | null;
          final_tb?: string | null;
          gender?: string | null;
          match_date?: string | null;
          match_id?: string;
          match_time?: string | null;
          player1?: string | null;
          player1_hand?: string | null;
          player2?: string | null;
          player2_hand?: string | null;
          round?: string | null;
          surface?: string | null;
          tournament?: string | null;
          umpire?: string | null;
        };
        Relationships: [];
      };
      mindset_boundaries: {
        Row: {
          coach_sees_patterns: boolean;
          paused_until: string | null;
          player_id: string;
          quiet_match_mornings: boolean;
          updated_at: string;
        };
        Insert: {
          coach_sees_patterns?: boolean;
          paused_until?: string | null;
          player_id: string;
          quiet_match_mornings?: boolean;
          updated_at?: string;
        };
        Update: {
          coach_sees_patterns?: boolean;
          paused_until?: string | null;
          player_id?: string;
          quiet_match_mornings?: boolean;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'mindset_boundaries_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: true;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      notes: {
        Row: {
          audio_delete_cause: string | null;
          audio_deleted_at: string | null;
          audio_ref: string | null;
          audio_uploaded_at: string | null;
          coach_share: boolean;
          cond: Json | null;
          created_at: string;
          ctx: string;
          deleted_at: string | null;
          device: string | null;
          dur_seconds: number;
          edits: Json;
          extraction: Json | null;
          id: string;
          lang: string | null;
          lang_conf: number | null;
          lang_source: string | null;
          mood: string | null;
          opponent: string | null;
          player_id: string;
          recorded_at: string;
          result: string | null;
          round: string | null;
          status: string;
          summary: string | null;
          surface: string | null;
          tags: Json;
          transcript: string | null;
          transcript_confirmed_at: string | null;
          transcript_raw: string | null;
          transcription: Json | null;
          updated_at: string;
          used: Json;
        };
        Insert: {
          audio_delete_cause?: string | null;
          audio_deleted_at?: string | null;
          audio_ref?: string | null;
          audio_uploaded_at?: string | null;
          coach_share?: boolean;
          cond?: Json | null;
          created_at?: string;
          ctx: string;
          deleted_at?: string | null;
          device?: string | null;
          dur_seconds?: number;
          edits?: Json;
          extraction?: Json | null;
          id?: string;
          lang?: string | null;
          lang_conf?: number | null;
          lang_source?: string | null;
          mood?: string | null;
          opponent?: string | null;
          player_id: string;
          recorded_at?: string;
          result?: string | null;
          round?: string | null;
          status?: string;
          summary?: string | null;
          surface?: string | null;
          tags?: Json;
          transcript?: string | null;
          transcript_confirmed_at?: string | null;
          transcript_raw?: string | null;
          transcription?: Json | null;
          updated_at?: string;
          used?: Json;
        };
        Update: {
          audio_delete_cause?: string | null;
          audio_deleted_at?: string | null;
          audio_ref?: string | null;
          audio_uploaded_at?: string | null;
          coach_share?: boolean;
          cond?: Json | null;
          created_at?: string;
          ctx?: string;
          deleted_at?: string | null;
          device?: string | null;
          dur_seconds?: number;
          edits?: Json;
          extraction?: Json | null;
          id?: string;
          lang?: string | null;
          lang_conf?: number | null;
          lang_source?: string | null;
          mood?: string | null;
          opponent?: string | null;
          player_id?: string;
          recorded_at?: string;
          result?: string | null;
          round?: string | null;
          status?: string;
          summary?: string | null;
          surface?: string | null;
          tags?: Json;
          transcript?: string | null;
          transcript_confirmed_at?: string | null;
          transcript_raw?: string | null;
          transcription?: Json | null;
          updated_at?: string;
          used?: Json;
        };
        Relationships: [
          {
            foreignKeyName: 'notes_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      notifications: {
        Row: {
          action_href: string | null;
          agent: string;
          body: string;
          category: string;
          created_at: string;
          id: string;
          player_id: string;
          read: boolean;
          title: string;
        };
        Insert: {
          action_href?: string | null;
          agent: string;
          body: string;
          category: string;
          created_at?: string;
          id?: string;
          player_id: string;
          read?: boolean;
          title: string;
        };
        Update: {
          action_href?: string | null;
          agent?: string;
          body?: string;
          category?: string;
          created_at?: string;
          id?: string;
          player_id?: string;
          read?: boolean;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      patterns: {
        Row: {
          coach_share: boolean;
          confidence: string;
          created_at: string;
          dismissed: boolean;
          dismissed_at: string | null;
          evidence: Json;
          explanation: string;
          id: string;
          kind: string;
          player_id: string;
          recur_since: number;
          rule_key: string;
          statement: string;
          tag: string;
          updated_at: string;
        };
        Insert: {
          coach_share?: boolean;
          confidence: string;
          created_at?: string;
          dismissed?: boolean;
          dismissed_at?: string | null;
          evidence?: Json;
          explanation: string;
          id?: string;
          kind: string;
          player_id: string;
          recur_since?: number;
          rule_key: string;
          statement: string;
          tag: string;
          updated_at?: string;
        };
        Update: {
          coach_share?: boolean;
          confidence?: string;
          created_at?: string;
          dismissed?: boolean;
          dismissed_at?: string | null;
          evidence?: Json;
          explanation?: string;
          id?: string;
          kind?: string;
          player_id?: string;
          recur_since?: number;
          rule_key?: string;
          statement?: string;
          tag?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'patterns_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      players: {
        Row: {
          app_language: string;
          billing_cycle: string | null;
          blocked_dates: string | null;
          country: string;
          dashboard_state: string;
          date_format: string;
          deletion_cancelled_at: string | null;
          deletion_confirmation_sent_at: string | null;
          deletion_confirmation_token: string | null;
          deletion_effective_at: string | null;
          deletion_requested_at: string | null;
          dob: string;
          email: string;
          emergency_contact: string | null;
          export_delivered_at: string | null;
          export_requested_at: string | null;
          guardian_confirmed_at: string | null;
          guardian_email: string | null;
          handed: string | null;
          home_currency: string;
          id: string;
          itf_id: string | null;
          itf_rank: number | null;
          key_tournaments: string[];
          name: string;
          notification_prefs: Json;
          onboarding_finished_at: string | null;
          onboarding_started_at: string | null;
          patron_language: string | null;
          quiet_hours_end: string;
          quiet_hours_start: string;
          reserve_reminder_enabled: boolean;
          spoken_language: string;
          stage: string | null;
          stage_pinned: boolean;
          surfaces: string[];
          target_rank: number | null;
          tier: string | null;
          tier_status: string | null;
          timezone: string;
          tour: string;
          tour_player_id: string | null;
          tour_points: number | null;
          tour_rank: number | null;
          units: string;
          verification: string;
          verification_source: string | null;
          weekly_budget: number | null;
          wtn: number | null;
        };
        Insert: {
          app_language: string;
          billing_cycle?: string | null;
          blocked_dates?: string | null;
          country: string;
          dashboard_state?: string;
          date_format?: string;
          deletion_cancelled_at?: string | null;
          deletion_confirmation_sent_at?: string | null;
          deletion_confirmation_token?: string | null;
          deletion_effective_at?: string | null;
          deletion_requested_at?: string | null;
          dob: string;
          email: string;
          emergency_contact?: string | null;
          export_delivered_at?: string | null;
          export_requested_at?: string | null;
          guardian_confirmed_at?: string | null;
          guardian_email?: string | null;
          handed?: string | null;
          home_currency: string;
          id: string;
          itf_id?: string | null;
          itf_rank?: number | null;
          key_tournaments?: string[];
          name: string;
          notification_prefs?: Json;
          onboarding_finished_at?: string | null;
          onboarding_started_at?: string | null;
          patron_language?: string | null;
          quiet_hours_end?: string;
          quiet_hours_start?: string;
          reserve_reminder_enabled?: boolean;
          spoken_language?: string;
          stage?: string | null;
          stage_pinned?: boolean;
          surfaces?: string[];
          target_rank?: number | null;
          tier?: string | null;
          tier_status?: string | null;
          timezone: string;
          tour: string;
          tour_player_id?: string | null;
          tour_points?: number | null;
          tour_rank?: number | null;
          units: string;
          verification?: string;
          verification_source?: string | null;
          weekly_budget?: number | null;
          wtn?: number | null;
        };
        Update: {
          app_language?: string;
          billing_cycle?: string | null;
          blocked_dates?: string | null;
          country?: string;
          dashboard_state?: string;
          date_format?: string;
          deletion_cancelled_at?: string | null;
          deletion_confirmation_sent_at?: string | null;
          deletion_confirmation_token?: string | null;
          deletion_effective_at?: string | null;
          deletion_requested_at?: string | null;
          dob?: string;
          email?: string;
          emergency_contact?: string | null;
          export_delivered_at?: string | null;
          export_requested_at?: string | null;
          guardian_confirmed_at?: string | null;
          guardian_email?: string | null;
          handed?: string | null;
          home_currency?: string;
          id?: string;
          itf_id?: string | null;
          itf_rank?: number | null;
          key_tournaments?: string[];
          name?: string;
          notification_prefs?: Json;
          onboarding_finished_at?: string | null;
          onboarding_started_at?: string | null;
          patron_language?: string | null;
          quiet_hours_end?: string;
          quiet_hours_start?: string;
          reserve_reminder_enabled?: boolean;
          spoken_language?: string;
          stage?: string | null;
          stage_pinned?: boolean;
          surfaces?: string[];
          target_rank?: number | null;
          tier?: string | null;
          tier_status?: string | null;
          timezone?: string;
          tour?: string;
          tour_player_id?: string | null;
          tour_points?: number | null;
          tour_rank?: number | null;
          units?: string;
          verification?: string;
          verification_source?: string | null;
          weekly_budget?: number | null;
          wtn?: number | null;
        };
        Relationships: [];
      };
      points: {
        Row: {
          first_serve: string | null;
          gender: string | null;
          gm_num: number | null;
          gm1: number | null;
          gm2: number | null;
          id: number;
          match_id: string | null;
          notes: string | null;
          pt: number | null;
          pt_winner: number | null;
          pts: string | null;
          second_serve: string | null;
          set1: number | null;
          set2: number | null;
          svr: number | null;
          tb_set: boolean | null;
        };
        Insert: {
          first_serve?: string | null;
          gender?: string | null;
          gm_num?: number | null;
          gm1?: number | null;
          gm2?: number | null;
          id?: number;
          match_id?: string | null;
          notes?: string | null;
          pt?: number | null;
          pt_winner?: number | null;
          pts?: string | null;
          second_serve?: string | null;
          set1?: number | null;
          set2?: number | null;
          svr?: number | null;
          tb_set?: boolean | null;
        };
        Update: {
          first_serve?: string | null;
          gender?: string | null;
          gm_num?: number | null;
          gm1?: number | null;
          gm2?: number | null;
          id?: number;
          match_id?: string | null;
          notes?: string | null;
          pt?: number | null;
          pt_winner?: number | null;
          pts?: string | null;
          second_serve?: string | null;
          set1?: number | null;
          set2?: number | null;
          svr?: number | null;
          tb_set?: boolean | null;
        };
        Relationships: [];
      };
      prize_receivables: {
        Row: {
          created_at: string;
          currency: string;
          event: string;
          expected_date: string;
          gross_amount: number;
          id: string;
          player_id: string;
          player_share: number;
          realised_home_currency: string | null;
          realised_rate: number | null;
          received_at: string | null;
          round: string;
          status: string;
          tournament_id: string | null;
          withholding_amount: number;
        };
        Insert: {
          created_at?: string;
          currency: string;
          event: string;
          expected_date: string;
          gross_amount: number;
          id?: string;
          player_id: string;
          player_share?: number;
          realised_home_currency?: string | null;
          realised_rate?: number | null;
          received_at?: string | null;
          round: string;
          status?: string;
          tournament_id?: string | null;
          withholding_amount?: number;
        };
        Update: {
          created_at?: string;
          currency?: string;
          event?: string;
          expected_date?: string;
          gross_amount?: number;
          id?: string;
          player_id?: string;
          player_share?: number;
          realised_home_currency?: string | null;
          realised_rate?: number | null;
          received_at?: string | null;
          round?: string;
          status?: string;
          tournament_id?: string | null;
          withholding_amount?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'prize_receivables_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      provider_switches: {
        Row: {
          changed_at: string;
          changed_by: string | null;
          id: string;
          provider: string;
          reason: string | null;
          state: string;
        };
        Insert: {
          changed_at?: string;
          changed_by?: string | null;
          id?: string;
          provider: string;
          reason?: string | null;
          state: string;
        };
        Update: {
          changed_at?: string;
          changed_by?: string | null;
          id?: string;
          provider?: string;
          reason?: string | null;
          state?: string;
        };
        Relationships: [];
      };
      ranking_snapshots: {
        Row: {
          country: string;
          created_at: string;
          id: string;
          itf_id: string | null;
          itf_points: number | null;
          itf_rank: number | null;
          name: string;
          player_id: string | null;
          points_by_tournament: Json;
          source: string;
          tour: string;
          tour_doubles_points: number | null;
          tour_doubles_rank: number | null;
          tour_player_id: string | null;
          tour_singles_points: number | null;
          tour_singles_rank: number | null;
          week_start: string;
        };
        Insert: {
          country: string;
          created_at?: string;
          id?: string;
          itf_id?: string | null;
          itf_points?: number | null;
          itf_rank?: number | null;
          name: string;
          player_id?: string | null;
          points_by_tournament?: Json;
          source?: string;
          tour: string;
          tour_doubles_points?: number | null;
          tour_doubles_rank?: number | null;
          tour_player_id?: string | null;
          tour_singles_points?: number | null;
          tour_singles_rank?: number | null;
          week_start: string;
        };
        Update: {
          country?: string;
          created_at?: string;
          id?: string;
          itf_id?: string | null;
          itf_points?: number | null;
          itf_rank?: number | null;
          name?: string;
          player_id?: string | null;
          points_by_tournament?: Json;
          source?: string;
          tour?: string;
          tour_doubles_points?: number | null;
          tour_doubles_rank?: number | null;
          tour_player_id?: string | null;
          tour_singles_points?: number | null;
          tour_singles_rank?: number | null;
          week_start?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ranking_snapshots_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      reserve_entries: {
        Row: {
          amount: number;
          cause: string;
          currency: string;
          device: string | null;
          entered_at: string;
          id: string;
          player_id: string;
          previous_amount: number | null;
        };
        Insert: {
          amount: number;
          cause: string;
          currency: string;
          device?: string | null;
          entered_at?: string;
          id?: string;
          player_id: string;
          previous_amount?: number | null;
        };
        Update: {
          amount?: number;
          cause?: string;
          currency?: string;
          device?: string | null;
          entered_at?: string;
          id?: string;
          player_id?: string;
          previous_amount?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: 'reserve_entries_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      share_links: {
        Row: {
          created_at: string;
          expires_at: string;
          id: string;
          last_opened_at: string | null;
          open_count: number;
          player_id: string;
          renewed_at: string | null;
          revoked: boolean;
          scope: string;
          token: string;
        };
        Insert: {
          created_at?: string;
          expires_at: string;
          id?: string;
          last_opened_at?: string | null;
          open_count?: number;
          player_id: string;
          renewed_at?: string | null;
          revoked?: boolean;
          scope: string;
          token: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          id?: string;
          last_opened_at?: string | null;
          open_count?: number;
          player_id?: string;
          renewed_at?: string | null;
          revoked?: boolean;
          scope?: string;
          token?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'share_links_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      snapshot_imports: {
        Row: {
          applied_at: string;
          applied_by: string | null;
          file_hash: string;
          id: string;
          matched: number;
          rows: number;
          stage_changes: number;
          unmatched: Json;
        };
        Insert: {
          applied_at?: string;
          applied_by?: string | null;
          file_hash: string;
          id?: string;
          matched?: number;
          rows: number;
          stage_changes?: number;
          unmatched?: Json;
        };
        Update: {
          applied_at?: string;
          applied_by?: string | null;
          file_hash?: string;
          id?: string;
          matched?: number;
          rows?: number;
          stage_changes?: number;
          unmatched?: Json;
        };
        Relationships: [];
      };
      stats_overview: {
        Row: {
          aces: number | null;
          bk_pts: number | null;
          bp_saved: number | null;
          dfs: number | null;
          first_in: number | null;
          first_won: number | null;
          gender: string | null;
          id: number;
          match_id: string | null;
          player: string | null;
          return_pts: number | null;
          return_pts_won: number | null;
          second_in: number | null;
          second_won: number | null;
          serve_pts: number | null;
          set_label: string | null;
          unforced: number | null;
          unforced_bh: number | null;
          unforced_fh: number | null;
          winners: number | null;
          winners_bh: number | null;
          winners_fh: number | null;
        };
        Insert: {
          aces?: number | null;
          bk_pts?: number | null;
          bp_saved?: number | null;
          dfs?: number | null;
          first_in?: number | null;
          first_won?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          return_pts?: number | null;
          return_pts_won?: number | null;
          second_in?: number | null;
          second_won?: number | null;
          serve_pts?: number | null;
          set_label?: string | null;
          unforced?: number | null;
          unforced_bh?: number | null;
          unforced_fh?: number | null;
          winners?: number | null;
          winners_bh?: number | null;
          winners_fh?: number | null;
        };
        Update: {
          aces?: number | null;
          bk_pts?: number | null;
          bp_saved?: number | null;
          dfs?: number | null;
          first_in?: number | null;
          first_won?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          return_pts?: number | null;
          return_pts_won?: number | null;
          second_in?: number | null;
          second_won?: number | null;
          serve_pts?: number | null;
          set_label?: string | null;
          unforced?: number | null;
          unforced_bh?: number | null;
          unforced_fh?: number | null;
          winners?: number | null;
          winners_bh?: number | null;
          winners_fh?: number | null;
        };
        Relationships: [];
      };
      stats_rally: {
        Row: {
          gender: string | null;
          id: number;
          match_id: string | null;
          pl1_forced: number | null;
          pl1_unforced: number | null;
          pl1_winners: number | null;
          pl1_won: number | null;
          pl2_forced: number | null;
          pl2_unforced: number | null;
          pl2_winners: number | null;
          pl2_won: number | null;
          pts: number | null;
          returner: string | null;
          row: string | null;
          server: string | null;
        };
        Insert: {
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          pl1_forced?: number | null;
          pl1_unforced?: number | null;
          pl1_winners?: number | null;
          pl1_won?: number | null;
          pl2_forced?: number | null;
          pl2_unforced?: number | null;
          pl2_winners?: number | null;
          pl2_won?: number | null;
          pts?: number | null;
          returner?: string | null;
          row?: string | null;
          server?: string | null;
        };
        Update: {
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          pl1_forced?: number | null;
          pl1_unforced?: number | null;
          pl1_winners?: number | null;
          pl1_won?: number | null;
          pl2_forced?: number | null;
          pl2_unforced?: number | null;
          pl2_winners?: number | null;
          pl2_won?: number | null;
          pts?: number | null;
          returner?: string | null;
          row?: string | null;
          server?: string | null;
        };
        Relationships: [];
      };
      stats_serve_basics: {
        Row: {
          aces: number | null;
          body: number | null;
          forced_err: number | null;
          gender: string | null;
          id: number;
          match_id: string | null;
          player: string | null;
          pts: number | null;
          pts_won: number | null;
          pts_won_lte_3: number | null;
          row: string | null;
          t: number | null;
          unret: number | null;
          wide: number | null;
        };
        Insert: {
          aces?: number | null;
          body?: number | null;
          forced_err?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          pts?: number | null;
          pts_won?: number | null;
          pts_won_lte_3?: number | null;
          row?: string | null;
          t?: number | null;
          unret?: number | null;
          wide?: number | null;
        };
        Update: {
          aces?: number | null;
          body?: number | null;
          forced_err?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          pts?: number | null;
          pts_won?: number | null;
          pts_won_lte_3?: number | null;
          row?: string | null;
          t?: number | null;
          unret?: number | null;
          wide?: number | null;
        };
        Relationships: [];
      };
      tournaments: {
        Row: {
          acceptance_status: string | null;
          altitude_m: number | null;
          ball: string | null;
          city: string | null;
          country: string | null;
          created_at: string;
          end_date: string;
          entry_deadline: string | null;
          id: string;
          indoor_outdoor: string | null;
          last_year_cut: number | null;
          lat: number | null;
          lon: number | null;
          name: string;
          points_table: Json;
          prize_table: Json;
          start_date: string;
          surface: string | null;
          tier: string | null;
          tour: string;
          updated_at: string;
        };
        Insert: {
          acceptance_status?: string | null;
          altitude_m?: number | null;
          ball?: string | null;
          city?: string | null;
          country?: string | null;
          created_at?: string;
          end_date: string;
          entry_deadline?: string | null;
          id?: string;
          indoor_outdoor?: string | null;
          last_year_cut?: number | null;
          lat?: number | null;
          lon?: number | null;
          name: string;
          points_table?: Json;
          prize_table?: Json;
          start_date: string;
          surface?: string | null;
          tier?: string | null;
          tour: string;
          updated_at?: string;
        };
        Update: {
          acceptance_status?: string | null;
          altitude_m?: number | null;
          ball?: string | null;
          city?: string | null;
          country?: string | null;
          created_at?: string;
          end_date?: string;
          entry_deadline?: string | null;
          id?: string;
          indoor_outdoor?: string | null;
          last_year_cut?: number | null;
          lat?: number | null;
          lon?: number | null;
          name?: string;
          points_table?: Json;
          prize_table?: Json;
          start_date?: string;
          surface?: string | null;
          tier?: string | null;
          tour?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      notes_saved_this_month: { Args: never; Returns: number };
      notes_saved_this_month_for: {
        Args: { p_player_id: string };
        Returns: number;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
