// Generated by the Supabase MCP server from the ProCircuit project schema
// (gpzpmrumwaqyfkyvqbgl) after migration 20260920090637_step_0_2_fix_function_search_path.
// Do not hand-edit; regenerate after each migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      admin_actions: {
        Row: {
          action_type: string;
          admin_id: string;
          consequence: string;
          created_at: string;
          device: string | null;
          id: string;
          notified_player: boolean;
          player_id: string | null;
          reason: string | null;
          role_at_time: string;
          target: Json | null;
        };
        Insert: {
          action_type: string;
          admin_id: string;
          consequence: string;
          created_at?: string;
          device?: string | null;
          id?: string;
          notified_player?: boolean;
          player_id?: string | null;
          reason?: string | null;
          role_at_time: string;
          target?: Json | null;
        };
        Update: {
          action_type?: string;
          admin_id?: string;
          consequence?: string;
          created_at?: string;
          device?: string | null;
          id?: string;
          notified_player?: boolean;
          player_id?: string | null;
          reason?: string | null;
          role_at_time?: string;
          target?: Json | null;
        };
        Relationships: [
          {
            foreignKeyName: 'admin_actions_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      agent_runs: {
        Row: {
          agent_name: string;
          completed_at: string | null;
          cost_amount: number | null;
          cost_currency: string | null;
          id: string;
          inputs_hash: string;
          model: string;
          output: Json | null;
          player_id: string;
          prompt_version: string;
          schema_version: string;
          started_at: string;
          status: string;
          trigger_type: string;
        };
        Insert: {
          agent_name: string;
          completed_at?: string | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          id?: string;
          inputs_hash: string;
          model: string;
          output?: Json | null;
          player_id: string;
          prompt_version: string;
          schema_version: string;
          started_at: string;
          status: string;
          trigger_type: string;
        };
        Update: {
          agent_name?: string;
          completed_at?: string | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          id?: string;
          inputs_hash?: string;
          model?: string;
          output?: Json | null;
          player_id?: string;
          prompt_version?: string;
          schema_version?: string;
          started_at?: string;
          status?: string;
          trigger_type?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'agent_runs_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      approvals: {
        Row: {
          action_type: string;
          agent_run_id: string | null;
          approved_at: string;
          approved_by: string;
          device: string | null;
          id: string;
          payload: Json;
          player_id: string;
        };
        Insert: {
          action_type: string;
          agent_run_id?: string | null;
          approved_at?: string;
          approved_by: string;
          device?: string | null;
          id?: string;
          payload: Json;
          player_id: string;
        };
        Update: {
          action_type?: string;
          agent_run_id?: string | null;
          approved_at?: string;
          approved_by?: string;
          device?: string | null;
          id?: string;
          payload?: Json;
          player_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'approvals_agent_run_id_fkey';
            columns: ['agent_run_id'];
            isOneToOne: false;
            referencedRelation: 'agent_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approvals_approved_by_fkey';
            columns: ['approved_by'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'approvals_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      fx_rates_daily: {
        Row: {
          currency: string;
          date: string;
          fetched_at: string;
          rate_to_eur: number;
          source: string;
        };
        Insert: {
          currency: string;
          date: string;
          fetched_at?: string;
          rate_to_eur: number;
          source: string;
        };
        Update: {
          currency?: string;
          date?: string;
          fetched_at?: string;
          rate_to_eur?: number;
          source?: string;
        };
        Relationships: [];
      };
      matches: {
        Row: {
          best_of: number | null;
          charted_by: string | null;
          court: string | null;
          final_tb: string | null;
          gender: string | null;
          match_date: string | null;
          match_id: string;
          match_time: string | null;
          player1: string | null;
          player1_hand: string | null;
          player2: string | null;
          player2_hand: string | null;
          round: string | null;
          surface: string | null;
          tournament: string | null;
          umpire: string | null;
        };
        Insert: {
          best_of?: number | null;
          charted_by?: string | null;
          court?: string | null;
          final_tb?: string | null;
          gender?: string | null;
          match_date?: string | null;
          match_id: string;
          match_time?: string | null;
          player1?: string | null;
          player1_hand?: string | null;
          player2?: string | null;
          player2_hand?: string | null;
          round?: string | null;
          surface?: string | null;
          tournament?: string | null;
          umpire?: string | null;
        };
        Update: {
          best_of?: number | null;
          charted_by?: string | null;
          court?: string | null;
          final_tb?: string | null;
          gender?: string | null;
          match_date?: string | null;
          match_id?: string;
          match_time?: string | null;
          player1?: string | null;
          player1_hand?: string | null;
          player2?: string | null;
          player2_hand?: string | null;
          round?: string | null;
          surface?: string | null;
          tournament?: string | null;
          umpire?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          action_href: string | null;
          agent: string;
          body: string;
          category: string;
          created_at: string;
          id: string;
          player_id: string;
          read: boolean;
          title: string;
        };
        Insert: {
          action_href?: string | null;
          agent: string;
          body: string;
          category: string;
          created_at?: string;
          id?: string;
          player_id: string;
          read?: boolean;
          title: string;
        };
        Update: {
          action_href?: string | null;
          agent?: string;
          body?: string;
          category?: string;
          created_at?: string;
          id?: string;
          player_id?: string;
          read?: boolean;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      players: {
        Row: {
          app_language: string;
          country: string;
          deletion_cancelled_at: string | null;
          deletion_effective_at: string | null;
          deletion_requested_at: string | null;
          dob: string;
          email: string;
          guardian_confirmed_at: string | null;
          guardian_email: string | null;
          home_currency: string;
          id: string;
          name: string;
          patron_language: string | null;
          stage: string | null;
          stage_pinned: boolean;
          tier: string | null;
          tier_status: string | null;
          timezone: string;
          tour: string;
          units: string;
          verification: string;
          verification_source: string | null;
        };
        Insert: {
          app_language: string;
          country: string;
          deletion_cancelled_at?: string | null;
          deletion_effective_at?: string | null;
          deletion_requested_at?: string | null;
          dob: string;
          email: string;
          guardian_confirmed_at?: string | null;
          guardian_email?: string | null;
          home_currency: string;
          id: string;
          name: string;
          patron_language?: string | null;
          stage?: string | null;
          stage_pinned?: boolean;
          tier?: string | null;
          tier_status?: string | null;
          timezone: string;
          tour: string;
          units: string;
          verification?: string;
          verification_source?: string | null;
        };
        Update: {
          app_language?: string;
          country?: string;
          deletion_cancelled_at?: string | null;
          deletion_effective_at?: string | null;
          deletion_requested_at?: string | null;
          dob?: string;
          email?: string;
          guardian_confirmed_at?: string | null;
          guardian_email?: string | null;
          home_currency?: string;
          id?: string;
          name?: string;
          patron_language?: string | null;
          stage?: string | null;
          stage_pinned?: boolean;
          tier?: string | null;
          tier_status?: string | null;
          timezone?: string;
          tour?: string;
          units?: string;
          verification?: string;
          verification_source?: string | null;
        };
        Relationships: [];
      };
      points: {
        Row: {
          first_serve: string | null;
          gender: string | null;
          gm_num: number | null;
          gm1: number | null;
          gm2: number | null;
          id: number;
          match_id: string | null;
          notes: string | null;
          pt: number | null;
          pt_winner: number | null;
          pts: string | null;
          second_serve: string | null;
          set1: number | null;
          set2: number | null;
          svr: number | null;
          tb_set: boolean | null;
        };
        Insert: {
          first_serve?: string | null;
          gender?: string | null;
          gm_num?: number | null;
          gm1?: number | null;
          gm2?: number | null;
          id?: number;
          match_id?: string | null;
          notes?: string | null;
          pt?: number | null;
          pt_winner?: number | null;
          pts?: string | null;
          second_serve?: string | null;
          set1?: number | null;
          set2?: number | null;
          svr?: number | null;
          tb_set?: boolean | null;
        };
        Update: {
          first_serve?: string | null;
          gender?: string | null;
          gm_num?: number | null;
          gm1?: number | null;
          gm2?: number | null;
          id?: number;
          match_id?: string | null;
          notes?: string | null;
          pt?: number | null;
          pt_winner?: number | null;
          pts?: string | null;
          second_serve?: string | null;
          set1?: number | null;
          set2?: number | null;
          svr?: number | null;
          tb_set?: boolean | null;
        };
        Relationships: [];
      };
      share_links: {
        Row: {
          created_at: string;
          expires_at: string;
          id: string;
          last_opened_at: string | null;
          open_count: number;
          player_id: string;
          renewed_at: string | null;
          revoked: boolean;
          scope: string;
          token: string;
        };
        Insert: {
          created_at?: string;
          expires_at: string;
          id?: string;
          last_opened_at?: string | null;
          open_count?: number;
          player_id: string;
          renewed_at?: string | null;
          revoked?: boolean;
          scope: string;
          token: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          id?: string;
          last_opened_at?: string | null;
          open_count?: number;
          player_id?: string;
          renewed_at?: string | null;
          revoked?: boolean;
          scope?: string;
          token?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'share_links_player_id_fkey';
            columns: ['player_id'];
            isOneToOne: false;
            referencedRelation: 'players';
            referencedColumns: ['id'];
          },
        ];
      };
      stats_overview: {
        Row: {
          aces: number | null;
          bk_pts: number | null;
          bp_saved: number | null;
          dfs: number | null;
          first_in: number | null;
          first_won: number | null;
          gender: string | null;
          id: number;
          match_id: string | null;
          player: string | null;
          return_pts: number | null;
          return_pts_won: number | null;
          second_in: number | null;
          second_won: number | null;
          serve_pts: number | null;
          set_label: string | null;
          unforced: number | null;
          unforced_bh: number | null;
          unforced_fh: number | null;
          winners: number | null;
          winners_bh: number | null;
          winners_fh: number | null;
        };
        Insert: {
          aces?: number | null;
          bk_pts?: number | null;
          bp_saved?: number | null;
          dfs?: number | null;
          first_in?: number | null;
          first_won?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          return_pts?: number | null;
          return_pts_won?: number | null;
          second_in?: number | null;
          second_won?: number | null;
          serve_pts?: number | null;
          set_label?: string | null;
          unforced?: number | null;
          unforced_bh?: number | null;
          unforced_fh?: number | null;
          winners?: number | null;
          winners_bh?: number | null;
          winners_fh?: number | null;
        };
        Update: {
          aces?: number | null;
          bk_pts?: number | null;
          bp_saved?: number | null;
          dfs?: number | null;
          first_in?: number | null;
          first_won?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          return_pts?: number | null;
          return_pts_won?: number | null;
          second_in?: number | null;
          second_won?: number | null;
          serve_pts?: number | null;
          set_label?: string | null;
          unforced?: number | null;
          unforced_bh?: number | null;
          unforced_fh?: number | null;
          winners?: number | null;
          winners_bh?: number | null;
          winners_fh?: number | null;
        };
        Relationships: [];
      };
      stats_rally: {
        Row: {
          gender: string | null;
          id: number;
          match_id: string | null;
          pl1_forced: number | null;
          pl1_unforced: number | null;
          pl1_winners: number | null;
          pl1_won: number | null;
          pl2_forced: number | null;
          pl2_unforced: number | null;
          pl2_winners: number | null;
          pl2_won: number | null;
          pts: number | null;
          returner: string | null;
          row: string | null;
          server: string | null;
        };
        Insert: {
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          pl1_forced?: number | null;
          pl1_unforced?: number | null;
          pl1_winners?: number | null;
          pl1_won?: number | null;
          pl2_forced?: number | null;
          pl2_unforced?: number | null;
          pl2_winners?: number | null;
          pl2_won?: number | null;
          pts?: number | null;
          returner?: string | null;
          row?: string | null;
          server?: string | null;
        };
        Update: {
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          pl1_forced?: number | null;
          pl1_unforced?: number | null;
          pl1_winners?: number | null;
          pl1_won?: number | null;
          pl2_forced?: number | null;
          pl2_unforced?: number | null;
          pl2_winners?: number | null;
          pl2_won?: number | null;
          pts?: number | null;
          returner?: string | null;
          row?: string | null;
          server?: string | null;
        };
        Relationships: [];
      };
      stats_serve_basics: {
        Row: {
          aces: number | null;
          body: number | null;
          forced_err: number | null;
          gender: string | null;
          id: number;
          match_id: string | null;
          player: string | null;
          pts: number | null;
          pts_won: number | null;
          pts_won_lte_3: number | null;
          row: string | null;
          t: number | null;
          unret: number | null;
          wide: number | null;
        };
        Insert: {
          aces?: number | null;
          body?: number | null;
          forced_err?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          pts?: number | null;
          pts_won?: number | null;
          pts_won_lte_3?: number | null;
          row?: string | null;
          t?: number | null;
          unret?: number | null;
          wide?: number | null;
        };
        Update: {
          aces?: number | null;
          body?: number | null;
          forced_err?: number | null;
          gender?: string | null;
          id?: number;
          match_id?: string | null;
          player?: string | null;
          pts?: number | null;
          pts_won?: number | null;
          pts_won_lte_3?: number | null;
          row?: string | null;
          t?: number | null;
          unret?: number | null;
          wide?: number | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
